/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Case;
import model.CivilCase;
import model.CriminalCase;

/**
 *
 * @author Tejas Shahi
 */
public class CaseDetail extends javax.swing.JFrame {

    controller.CaseController controller = new controller.CaseController();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CaseDetail.class.getName());

    /**
     * Creates new form CaseDetail
     */
    public CaseDetail(Case c) {
        this.setSize(900, 800);
        initComponents();
        populateData(c);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Close only this window, not the whole app
    }

    private void populateData(Case c) {
        // 1. Populate Common Data
        lblCaseId.setText(String.valueOf(c.getCaseId()));
        lblTitle.setText(c.getCaseTitle());
        lblRegNo.setText(c.getRegistrationNumber());
        lblDate.setText(c.getHearingDate());
        lblJudge.setText(c.getAssignedJudge());
        lblType.setText(c.getCaseStatus());
        lblType.setText(c.getCaseType());

        // 2. Populate Specific Data based on Type
        if (c instanceof CivilCase) {
            CivilCase cc = (CivilCase) c;
            txtDetails.setText(
                    "Dispute Type: " + cc.getDisputeType() + "\n"
                    + "Subject Matter: " + cc.getSubjectMatter() + "\n"
                    + "Claim Amount: " + cc.getClaimAmount() + "\n"
                    + "Relief Sought: " + cc.getReliefSought()
            );
        } else if (c instanceof CriminalCase) {
            CriminalCase cc = (CriminalCase) c;
            txtDetails.setText(
                    "Crime Type: " + cc.getCrimeType() + "\n"
                    + "Police Station: " + cc.getPoliceStation() + "\n"
                    + "FIR Number: " + cc.getFirNumber() + "\n"
                    + "Bail Status: " + cc.getBailGranted()
            );
        }
    }

    public CaseDetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lblJudge = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lblCaseId = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblRegNo = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lblStatus1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetails = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblType = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 800));
        setMinimumSize(new java.awt.Dimension(915, 840));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Inter", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CASE DETAIL");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(330, 10, 240, 47);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 14));
        jPanel3.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Science Gothic", 0, 22)); // NOI18N
        jLabel28.setText("Case ID :");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(40, 20, 98, 29);

        jLabel29.setFont(new java.awt.Font("Science Gothic", 0, 22)); // NOI18N
        jLabel29.setText("Case Status :");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(450, 170, 190, 29);

        jLabel30.setFont(new java.awt.Font("Science Gothic", 0, 22)); // NOI18N
        jLabel30.setText("Reg No. :");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(40, 120, 98, 29);

        jLabel31.setFont(new java.awt.Font("Science Gothic", 0, 22)); // NOI18N
        jLabel31.setText("Case Title :");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(40, 70, 120, 29);

        jLabel32.setFont(new java.awt.Font("Science Gothic", 0, 22)); // NOI18N
        jLabel32.setText("Filing Date :");
        jPanel3.add(jLabel32);
        jLabel32.setBounds(450, 20, 130, 29);

        jLabel33.setFont(new java.awt.Font("Science Gothic", 0, 22)); // NOI18N
        jLabel33.setText("Hearing Date :");
        jPanel3.add(jLabel33);
        jLabel33.setBounds(450, 120, 150, 30);

        lblJudge.setFont(new java.awt.Font("Science Gothic", 0, 22)); // NOI18N
        lblJudge.setText("Kalpana Ghimire");
        jPanel3.add(lblJudge);
        lblJudge.setBounds(220, 170, 190, 29);

        jLabel35.setFont(new java.awt.Font("Science Gothic", 0, 22)); // NOI18N
        jLabel35.setText("Assigned judge :");
        jPanel3.add(jLabel35);
        jLabel35.setBounds(40, 170, 190, 29);

        lblCaseId.setFont(new java.awt.Font("Science Gothic", 0, 22)); // NOI18N
        lblCaseId.setText("101");
        jPanel3.add(lblCaseId);
        lblCaseId.setBounds(220, 20, 190, 29);

        lblTitle.setFont(new java.awt.Font("Science Gothic", 0, 22)); // NOI18N
        lblTitle.setText("Udaya vs Anish");
        jPanel3.add(lblTitle);
        lblTitle.setBounds(220, 70, 460, 29);

        lblRegNo.setFont(new java.awt.Font("Science Gothic", 0, 22)); // NOI18N
        lblRegNo.setText("Reg-101");
        jPanel3.add(lblRegNo);
        lblRegNo.setBounds(220, 120, 190, 29);

        lblDate.setFont(new java.awt.Font("Science Gothic", 0, 22)); // NOI18N
        lblDate.setText("2026-01-13");
        jPanel3.add(lblDate);
        lblDate.setBounds(620, 120, 190, 29);

        jLabel41.setFont(new java.awt.Font("Science Gothic", 0, 22)); // NOI18N
        jLabel41.setText("2024-08-23");
        jPanel3.add(jLabel41);
        jLabel41.setBounds(620, 20, 190, 29);

        lblStatus1.setFont(new java.awt.Font("Science Gothic", 0, 22)); // NOI18N
        lblStatus1.setText("Active");
        jPanel3.add(lblStatus1);
        lblStatus1.setBounds(620, 170, 190, 29);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 10, 860, 220);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 14));
        jPanel4.setLayout(null);

        txtDetails.setColumns(20);
        txtDetails.setRows(5);
        jScrollPane1.setViewportView(txtDetails);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(30, 30, 800, 380);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete Case");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel4.add(jButton2);
        jButton2.setBounds(310, 420, 130, 40);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Save as File");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel4.add(jButton3);
        jButton3.setBounds(460, 420, 130, 40);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(10, 240, 860, 480);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 60, 880, 730);

        lblType.setFont(new java.awt.Font("Science Gothic", 0, 22)); // NOI18N
        lblType.setForeground(new java.awt.Color(255, 255, 255));
        lblType.setText("CASE TYPE");
        jPanel1.add(lblType);
        lblType.setBounds(760, 10, 130, 29);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // 1. Get Case ID from the label
        // The text is "101", so we parse it to an integer
        String idText = lblCaseId.getText();

        if (idText.isEmpty() || idText.equals("-")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Invalid Case ID.");
            return;
        }

        int caseId = Integer.parseInt(idText);

        // 2. CONFIRMATION DIALOG (Safety Check)
        int choice = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete Case #" + caseId + "?\nThis will move it to the Recycle Bin.",
                "Confirm Deletion",
                javax.swing.JOptionPane.YES_NO_OPTION);

        // 3. EXECUTE DELETE
        if (choice == javax.swing.JOptionPane.YES_OPTION) {

            // Call the controller to delete (move to stack)
            boolean success = controller.deleteCase(caseId);

            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this, "Case moved to Recycle Bin.");

                // 4. CLOSE THIS WINDOW
                // This closes the detail popup and reveals the main dashboard again
                this.dispose();

            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: Could not delete case (Case not found or Stack full).");
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        //  Get the Case ID from the screen
        int caseId = Integer.parseInt(lblCaseId.getText());

        //  Find the object
        model.Case c = controller.findCaseById(caseId);

        if (c != null) {
            //  Call our simple save method
            boolean success = controller.saveCaseToTextFile(c);

            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this, "File Saved: Case_" + caseId + ".txt");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: Could not save file.");
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CaseDetail().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCaseId;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblJudge;
    private javax.swing.JLabel lblRegNo;
    private javax.swing.JLabel lblStatus1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextArea txtDetails;
    // End of variables declaration//GEN-END:variables
}
