/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


/**
 *
 * @author tejas
 */
public class LoginFr extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFr.class.getName());

    /**
     * Creates new form LoginFr
     */
    public LoginFr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 612));
        jPanel2.setLayout(null);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(292, 40, 0, 0);

        jLabel4.setFont(new java.awt.Font("Poppins Black", 0, 56)); // NOI18N
        jLabel4.setText("Login");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(520, 60, 160, 85);

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Sign in to continue.");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(550, 160, 103, 16);

        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
        });
        txtUsername.addActionListener(this::txtUsernameActionPerformed);
        jPanel2.add(txtUsername);
        txtUsername.setBounds(460, 220, 279, 42);

        jLabel6.setFont(new java.awt.Font("Adwaita Sans", 0, 12)); // NOI18N
        jLabel6.setText("USERNAME");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(460, 200, 67, 16);

        jLabel7.setFont(new java.awt.Font("Adwaita Sans", 0, 12)); // NOI18N
        jLabel7.setText("PASSWORD");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(460, 270, 80, 16);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel2.add(jButton1);
        jButton1.setBounds(440, 370, 327, 45);

        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(txtPassword);
        txtPassword.setBounds(460, 290, 279, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\MyProjects\\netbeans\\Cases_Management_System\\assets\\court.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel2)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(10, 10, 400, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = txtUsername.getText();
        String password = new String(txtPassword.getPassword());

        // Check 1: Is the Username empty?
        if (username.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Username cannot be empty. Please enter your ID.",
                "Validation Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // STOP here. Do not check password.
        }

        // Check 2: Is the Password empty?
        if (password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Password cannot be empty.",
                "Validation Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // STOP here.
        }
        // Check 3: Minimum Length (Optional but good for security marks)
        if (password.length() < 4) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Password must be at least 4 characters long.",
                "Validation Error",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ... (Your validation code for empty fields stays here) ...

        // 1. CHECK IF ADMIN (Hardcoded for safety/simplicity)
        if (username.equals("admin") && password.equals("admin")) {

            javax.swing.JOptionPane.showMessageDialog(this, "Hello Justice Maker, Welcome back.");
            AdminView dashboard = new AdminView();
            dashboard.setVisible(true);
            this.dispose();

        } else {
            // 2. CHECK IF JUDGE (Dynamic check against your list)
            controller.JudgeController jc = new controller.JudgeController();
            model.Judge loggedInJudge = jc.loginJudge(username, password);

            if (loggedInJudge != null) {
                // SUCCESS: Judge Found!
                javax.swing.JOptionPane.showMessageDialog(this, "Welcome, Judge " + loggedInJudge.getName());

                // Pass the specific judge object to the dashboard so they only see their cases
                view.JudgeDashboard judgeView = new view.JudgeDashboard(loggedInJudge);
                judgeView.setVisible(true);
                this.dispose();

            } else {
                // FAILURE: Neither Admin nor Judge
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Incorrect Username or Password.",
                    "Login Failed",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        if (txtUsername.getText().equals("Enter Username")) {
            // 2. Clear the text
            txtUsername.setText("");

            // 3. Optional: Change text color to black (if it was gray)
            txtUsername.setForeground(new java.awt.Color(0, 0, 0));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFr().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
